title: "LeonardoOna Scientific Group"
description: "A webpage for our scientific group inspired by Allesina Î»ab"
url: "https://LeonardoOna.github.io"
baseurl: ""  # Leave empty for a user site
theme: minima  # Or another theme if you prefer
plugins:
  - jekyll-seo-tag
